# Site settings
title: Polymeria UML
description: "Polymeria UML is a set of Polymer Web components for rendering an Eclipse UML2 model file."
baseurl: /polymeria
url: "http://bdulac.github.io/polymeria/"
github_username:  bdulac

# Build settings
markdown:	kramdown
permalink: :title

name: Bérenger Dulac
